#!/bin/bash
set -e

declare -a seeds=(0)
export LLM=Qwen2.5-3B-Instruct

for seed in ${seeds[@]}; do
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=llava-1.5-7b-hf,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vl_uncertainty,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=llava-1.5-7b-hf,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vauq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=llava-1.5-7b-hf,USE_MODEL_MANAGER=True,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=svar,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=MisbehaviorBench,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=euq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh

    # GMAIMMBench
    # bsub -env "SEED=${seed},BENCHMARK=GMAIMMBench,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vl_uncertainty,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=GMAIMMBench,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=euq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=GMAIMMBench,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vauq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=GMAIMMBench,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=svar,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=GMAIMMBench,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=nll,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=GMAIMMBench,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=pro,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=GMAIMMBench,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=rds,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=GMAIMMBench,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vse,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=GMAIMMBench,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vse_masked,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh

    # MedVIGIL
    # bsub -env "SEED=${seed},BENCHMARK=MedVIGIL,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vl_uncertainty,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=MedVIGIL,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=euq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=MedVIGIL,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vauq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=MedVIGIL,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=svar,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=MedVIGIL,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=nll,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=MedVIGIL,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=pro,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=MedVIGIL,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=rds,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=MedVIGIL,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vse,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=MedVIGIL,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vse_masked,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh

    # ViLP
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vl_uncertainty,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=euq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vauq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=True,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=svar,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=nll,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=pro,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=rds,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vse,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh
    # bsub -env "SEED=${seed},BENCHMARK=ViLP,LVLM=Qwen2.5-VL-7B-Instruct,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vse_masked,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=5" < ./vlu_test_job.sh

    # HAM10000
    bsub -env "SEED=${seed},BENCHMARK=HAM10000,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vl_uncertainty,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=10" < ./vlu_test_job.sh
    bsub -env "SEED=${seed},BENCHMARK=HAM10000,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=semantic_entropy,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=10" < ./vlu_test_job.sh
    bsub -env "SEED=${seed},BENCHMARK=HAM10000,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=euq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    bsub -env "SEED=${seed},BENCHMARK=HAM10000,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vauq,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    bsub -env "SEED=${seed},BENCHMARK=HAM10000,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=svar,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    bsub -env "SEED=${seed},BENCHMARK=HAM10000,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=nll,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=0" < ./vlu_test_job.sh
    bsub -env "SEED=${seed},BENCHMARK=HAM10000,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=pro,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=10" < ./vlu_test_job.sh
    bsub -env "SEED=${seed},BENCHMARK=HAM10000,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=rds,INFERENCE_TEMP=0.0,SAMPLING_TEMP=0.0,SAMPLING_TIME=10" < ./vlu_test_job.sh
    bsub -env "SEED=${seed},BENCHMARK=HAM10000,LVLM=medgemma-1.5-4b-it,USE_MODEL_MANAGER=False,USE_FASTEST=False,LLM=${LLM},UNCERTAINTY=vse,INFERENCE_TEMP=0.1,SAMPLING_TEMP=1.0,SAMPLING_TIME=10" < ./vlu_test_job.sh
done
